# Generated by Django 5.1.2 on 2024-10-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecando', '0002_alter_autor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
    ]
